runtime: python310
entrypoint: gunicorn -b :$PORT Click_Check_Chat_Buy.wsgi

runtime_config:
  python_version: 3

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.8
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
